### ISSUE TITLE
Sitemap av originalsidan

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/gak2023#10]
Analysera den befintliga webbsidan och gör en sitemap av den. Exempel på verktyg där detta är enkelt är Inkscape och Penpot.

**Comment by Einar12345** [comment]
[https://www.gloomaps.com/yisCFHbAhD](url)

![Image](https://user-images.githubusercontent.com/32792535/217226913-49608cb2-b82f-43b3-bdf6-d31662fcfeca.png)

**Comment by seetee** [comment]
Om informationen ovan är korrekt, välj "Close with comment" nedan.

**Comment by seetee** [comment]
Never mind, den är ju redan stängd. Ignorera mig.
