### ISSUE TITLE
Sitemap för nya sidan

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/gak2023#11]
Referera till sitemap för befintliga sidan men också de content types och taxonomies som är bestämda.

**Comment by zvyc** [comment]
Nya sidan:

Startsida
 - Välkomnande och kort info med länk till deras tidning aurora
 - Kanske någon mer allmän info om 
 - Teaser med senaste nyheter där titel och datum endast visas
 - Teaser med senaste event där titel och datum endast visas
Bli medlem + Nybörjarsida = Utbildning sida
 - Info om att bli medlem med avgifter
 - Även en guide för nya medlemmar'
Bildgalleri
 - Bilder from rymden med image content typen
Händelser
 - Hem till content typen händelser där alla händelser visas i en paginerad lista.
Observatoriet
 - Statisk sida med info om deras observatorium
Historia
 - Statisk sida med klubbens historia
Styrelsen
 - Alla i styrelsen med kontaktuppgifter
Aurora
 - Bilder på deras tidskrift aurora
Länkar
 - Meny med länkar till externa resurser

**Comment by zvyc** [comment]
Kanske slå ihop Observatoriumet och Historia till en "Om" sida

**Comment by joellundin** [comment]
![Image](https://user-images.githubusercontent.com/100196157/224968688-8062aff6-106c-4232-9692-d84f0aabd3a8.png)



![Image](https://user-images.githubusercontent.com/100196157/224968757-202133a7-8e01-4f6c-acfa-26cec4805683.png)

**Comment by joellundin** [comment]
Obs första bilden är en dörsta sida och andra bilden är hur sidan är menad att se ut om du skrollar ner.
