### ISSUE TITLE
Hitta stock-bilder

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/gak2023#4]
Analysera befintlig webbsida samt konkurrenter och fundera på vad för slags bildspråk som används. Leta upp stock-foton och samla så att de finns tillgängliga under projektet, både till moodboards, som exempelbilder men också som bakgrundsbilder och liknande. Se till att upphovsrätten efterlevs!

**Comment by seetee** [comment]
Om uppgiften är genomförd, notera hur detta skett och välj "Close with comment" nedan.

**Comment by roperopen** [comment]
Vi har genomfört detta moment. Det var jag och Edvin som satt och analysera vår gamla hemmsida och svenska astronmiska sällskapet flr inspiration. vi märkte att många av deras bilder och på den orginella GAK hemssidan var på stjärnor stjärnfall och meteorer och lite av de andra planeterna. Så vi gick in på pixabay och sökte efter massa häfrtiga sjärnfall, tjärnors och planeters bilder för att användas som bakgrundsbilder och för bildgallerian.
