### ISSUE TITLE
Skapa moodboard

### ISSUE THREAD

**Issue by seetee** [tcstenungsund/gak2023#6]
Analysera befintlig webbplats samt konkurrenter. Vad är syftet med sidan? Vilken känsla vill förmedlas? Skapa en moodboard, antingen fysiskt eller digitalt.

**Comment by Emmalandgren** [comment]
![Image](https://user-images.githubusercontent.com/119410929/234244175-9a167fe7-29e7-4977-9178-659de27d8719.png)
